import type {
  Idea, Project, ProjectCategory, CalendarEvent, HeritageItem,
} from './types'

export const mockIdeas: Idea[] = [
  {
    id: 'id1', title: 'Construction d\'un siège social pour l\'association',
    description: 'Acquérir un terrain et construire un bâtiment servant de siège permanent pour les activités de l\'association et la gestion administrative.',
    objective: 'Disposer d\'un lieu fixe pour les réunions, le stockage des archives et l\'accueil des membres.',
    category: 'Infrastructure', location: 'Douala, Cameroun',
    benefits: 'Renforcement de l\'identité de l\'association, centralisation des activités, valorisation patrimoniale.',
    estimatedBudget: 50000000, photos: [], documents: ['etude_faisabilite.pdf', 'plan_architecte.pdf'],
    author: 'Jean Menthong', createdAt: '2025-01-15', status: 'Transformée en projet',
    comments: [
      { id: 'c1', author: 'Paul Tchoumi', date: '2025-01-18', text: 'Excellente initiative. Il faut identifier un terrain abordable.' },
      { id: 'c2', author: 'Marie Kamga', date: '2025-01-22', text: 'Je propose qu\'on commence par une collecte pour le terrain.' },
      { id: 'c3', author: 'Robert Kana', date: '2025-02-01', text: 'Le bureau exécutif soutient cette idée à l\'unanimité.' },
    ],
    reactions: [
      { type: '👍', count: 24 }, { type: '❤️', count: 12 }, { type: '👏', count: 8 },
    ],
    supports: 18, views: 156,
    votes: { favorable: 22, unfavorable: 1, abstention: 3 },
    history: [
      { id: 'h1', date: '2025-01-15', event: 'Idée proposée par Jean Menthong', actor: 'Jean Menthong' },
      { id: 'h2', date: '2025-01-20', event: 'Statut changé: Nouvelle → En discussion', actor: 'Système' },
      { id: 'h3', date: '2025-02-05', event: 'Statut changé: En discussion → Soumise au vote', actor: 'Bureau exécutif' },
      { id: 'h4', date: '2025-02-15', event: 'Vote clôturé: 22 favorables, 1 défavorable, 3 abstentions', actor: 'Système' },
      { id: 'h5', date: '2025-02-16', event: 'Statut changé: Soumise au vote → Acceptée', actor: 'Bureau exécutif' },
      { id: 'h6', date: '2025-02-20', event: 'Transformée en projet PRJ-2025-001', actor: 'Jean Menthong' },
    ],
    priority: 'Élevée', transformedProjectId: 'p1',
  },
  {
    id: 'id2', title: 'Programme de mentorat pour les étudiants',
    description: 'Mettre en place un programme de mentorat reliant les membres expérimentés de la diaspora avec les étudiants de la communauté.',
    objective: 'Accompagner 20 étudiants par an dans leur parcours académique et professionnel.',
    category: 'Éducation', location: 'En ligne / International',
    benefits: 'Renforcement des compétences, insertion professionnelle facilitée, création de réseaux.',
    estimatedBudget: 2000000, photos: [], documents: ['schema_mentorat.pdf'],
    author: 'Christine Bélanger', createdAt: '2025-03-10', status: 'Acceptée',
    comments: [
      { id: 'c4', author: 'Prof. Samuel Njoya', date: '2025-03-12', text: 'Je suis prêt à être mentor en informatique.' },
      { id: 'c5', author: 'Sandra Ngono', date: '2025-03-15', text: 'Cette initiative tombe à pic pour moi, j\'aimerais être mentorée.' },
    ],
    reactions: [
      { type: '👍', count: 31 }, { type: '❤️', count: 15 }, { type: '👏', count: 10 },
    ],
    supports: 25, views: 98,
    votes: { favorable: 28, unfavorable: 0, abstention: 2 },
    history: [
      { id: 'h7', date: '2025-03-10', event: 'Idée proposée par Christine Bélanger', actor: 'Christine Bélanger' },
      { id: 'h8', date: '2025-03-15', event: 'Statut changé: Nouvelle → En discussion', actor: 'Système' },
      { id: 'h9', date: '2025-04-01', event: 'Statut changé: En discussion → Soumise au vote', actor: 'Bureau exécutif' },
      { id: 'h10', date: '2025-04-10', event: 'Statut changé: Soumise au vote → Acceptée', actor: 'Bureau exécutif' },
    ],
    priority: 'Moyenne', transformedProjectId: null,
  },
  {
    id: 'id3', title: 'Création d\'une ferme agricole communautaire',
    description: 'Acquérir un terrain agricole pour produire des cultures vivrières et générer des revenus pour l\'association.',
    objective: 'Autofinancement partiel de l\'association via la vente des récoltes.',
    category: 'Agriculture', location: 'Bafoussam, Cameroun',
    benefits: 'Revenus réguliers, création d\'emplois locaux, sécurité alimentaire.',
    estimatedBudget: 15000000, photos: [], documents: [],
    author: 'Robert Kana', createdAt: '2025-05-20', status: 'En discussion',
    comments: [
      { id: 'c6', author: 'Marc Fotso', date: '2025-05-22', text: 'Bonne idée, mais il faut une étude de marché pour les cultures rentables.' },
      { id: 'c7', author: 'Jean Menthong', date: '2025-05-25', text: 'Je connais un agronome qui pourrait nous aider.' },
    ],
    reactions: [
      { type: '👍', count: 15 }, { type: '❤️', count: 6 }, { type: '👏', count: 4 },
    ],
    supports: 12, views: 67,
    votes: { favorable: 0, unfavorable: 0, abstention: 0 },
    history: [
      { id: 'h11', date: '2025-05-20', event: 'Idée proposée par Robert Kana', actor: 'Robert Kana' },
      { id: 'h12', date: '2025-05-21', event: 'Statut changé: Nouvelle → En discussion', actor: 'Système' },
    ],
    priority: 'Moyenne', transformedProjectId: null,
  },
  {
    id: 'id4', title: 'Application mobile pour la gestion de l\'association',
    description: 'Développer une application mobile permettant aux membres de suivre les actualités, cotisations et événements.',
    objective: 'Faciliter la communication et l\'engagement des membres.',
    category: 'Technologie', location: 'En ligne',
    benefits: 'Meilleure communication, transparence, engagement accru des membres.',
    estimatedBudget: 5000000, photos: [], documents: ['cahier_des_charges.pdf'],
    author: 'Eric Fotso', createdAt: '2025-06-05', status: "À l'étude",
    comments: [
      { id: 'c8', author: 'Yvan Kamga', date: '2025-06-07', text: 'Je peux aider au développement en tant que stagiaire.' },
    ],
    reactions: [
      { type: '👍', count: 19 }, { type: '❤️', count: 8 }, { type: '👏', count: 5 },
    ],
    supports: 14, views: 82,
    votes: { favorable: 0, unfavorable: 0, abstention: 0 },
    history: [
      { id: 'h13', date: '2025-06-05', event: 'Idée proposée par Eric Fotso', actor: 'Eric Fotso' },
      { id: 'h14', date: '2025-06-10', event: 'Statut changé: Nouvelle → En discussion', actor: 'Système' },
      { id: 'h15', date: '2025-06-20', event: 'Statut changé: En discussion → À l\'étude', actor: 'Bureau exécutif' },
    ],
    priority: 'Faible', transformedProjectId: null,
  },
  {
    id: 'id5', title: 'Organisation d\'un gala annuel de fundraising',
    description: 'Organiser un gala annuel pour lever des fonds et renforcer les liens entre membres de la diaspora.',
    objective: 'Lever 10 000 000 FCFA par an et fédérer la communauté.',
    category: 'Événementiel', location: 'Paris, France',
    benefits: 'Financement des projets, visibilité de l\'association, renforcement des liens.',
    estimatedBudget: 3000000, photos: [], documents: [],
    author: 'Brigitte Ngo', createdAt: '2025-06-15', status: 'Soumise au vote',
    comments: [
      { id: 'c9', author: 'Christine Bélanger', date: '2025-06-16', text: 'Excellente idée, je peux aider pour l\'organisation à Montréal.' },
      { id: 'c10', author: 'Paul Tchoumi', date: '2025-06-18', text: 'Il faut un budget marketing conséquent pour attirer des sponsors.' },
    ],
    reactions: [
      { type: '👍', count: 27 }, { type: '❤️', count: 14 }, { type: '👏', count: 11 },
    ],
    supports: 20, views: 113,
    votes: { favorable: 15, unfavorable: 3, abstention: 5 },
    history: [
      { id: 'h16', date: '2025-06-15', event: 'Idée proposée par Brigitte Ngo', actor: 'Brigitte Ngo' },
      { id: 'h17', date: '2025-06-20', event: 'Statut changé: Nouvelle → En discussion', actor: 'Système' },
      { id: 'h18', date: '2025-07-01', event: 'Statut changé: En discussion → Soumise au vote', actor: 'Bureau exécutif' },
    ],
    priority: 'Élevée', transformedProjectId: null,
  },
  {
    id: 'id6', title: 'Caisse de microcrédit pour les membres',
    description: 'Mettre en place une caisse de microcrédit permettant aux membres de financer de petits projets entrepreneuriaux.',
    objective: 'Soutenir 10 micro-projets par an avec des prêts à taux réduit.',
    category: 'Finance', location: 'Douala, Cameroun',
    benefits: 'Entrepreneuriat, autonomisation financière, création d\'emplois.',
    estimatedBudget: 10000000, photos: [], documents: [],
    author: 'Paul Tchoumi', createdAt: '2025-07-01', status: 'Nouvelle',
    comments: [],
    reactions: [
      { type: '👍', count: 8 }, { type: '❤️', count: 3 }, { type: '👏', count: 2 },
    ],
    supports: 5, views: 34,
    votes: { favorable: 0, unfavorable: 0, abstention: 0 },
    history: [
      { id: 'h19', date: '2025-07-01', event: 'Idée proposée par Paul Tchoumi', actor: 'Paul Tchoumi' },
    ],
    priority: 'Moyenne', transformedProjectId: null,
  },
  {
    id: 'id7', title: 'Programme de formation en leadership pour les jeunes',
    description: 'Organiser des ateliers de formation en leadership et gestion de projets pour les jeunes membres.',
    objective: 'Former 30 jeunes par an au leadership et à la gestion associative.',
    category: 'Éducation', location: 'Bafoussam, Cameroun',
    benefits: 'Préparation de la relève, renforcement des compétences, engagement civique.',
    estimatedBudget: 1500000, photos: [], documents: [],
    author: 'Marie Kamga', createdAt: '2025-07-10', status: 'Refusée',
    comments: [
      { id: 'c11', author: 'Jean Menthong', date: '2025-07-12', text: 'L\'idée est bonne mais le budget est insuffisant pour un programme de qualité.' },
    ],
    reactions: [
      { type: '👍', count: 6 }, { type: '❤️', count: 2 }, { type: '👏', count: 1 },
    ],
    supports: 4, views: 28,
    votes: { favorable: 3, unfavorable: 12, abstention: 5 },
    history: [
      { id: 'h20', date: '2025-07-10', event: 'Idée proposée par Marie Kamga', actor: 'Marie Kamga' },
      { id: 'h21', date: '2025-07-15', event: 'Statut changé: Nouvelle → Soumise au vote', actor: 'Bureau exécutif' },
      { id: 'h22', date: '2025-07-22', event: 'Vote clôturé: 3 favorables, 12 défavorables, 5 abstentions', actor: 'Système' },
      { id: 'h23', date: '2025-07-23', event: 'Statut changé: Soumise au vote → Refusée', actor: 'Bureau exécutif' },
    ],
    priority: 'Faible', transformedProjectId: null,
  },
]

export const mockProjects: Project[] = [
  {
    id: 'p1', number: 'PRJ-2025-001', title: 'Construction d\'un siège social',
    description: 'Acquérir un terrain et construire un bâtiment servant de siège permanent pour l\'association.',
    category: 'Infrastructure', location: 'Douala, Cameroun',
    budget: 50000000, spent: 8500000, startDate: '2025-03-01', endDate: '2026-12-31',
    status: 'En cours', manager: 'Jean Menthong', team: ['Paul Tchoumi', 'Robert Kana', 'Marc Fotso'],
    progress: 17,
    tasks: [
      { id: 't1', label: 'Acquisition du terrain', done: true },
      { id: 't2', label: 'Étude de faisabilité', done: true },
      { id: 't3', label: 'Plans architecturaux', done: true },
      { id: 't4', label: 'Obtention des permis de construire', done: false },
      { id: 't5', label: 'Fouilles et fondations', done: false },
      { id: 't6', label: 'Gros œuvre', done: false },
      { id: 't7', label: 'Second œuvre', done: false },
      { id: 't8', label: 'Aménagements intérieurs', done: false },
    ],
    photos: [], documents: ['plan_architecte.pdf', 'devis_construction.pdf', 'titre_foncier.pdf'],
    sourceIdeaId: 'id1', heritage: false,
  },
  {
    id: 'p2', number: 'PRJ-2025-002', title: 'Programme de mentorat étudiants',
    description: 'Programme de mentorat reliant les membres expérimentés avec les étudiants de la communauté.',
    category: 'Éducation', location: 'En ligne / International',
    budget: 2000000, spent: 0, startDate: '2025-09-01', endDate: '2026-08-31',
    status: 'Planifié', manager: 'Christine Bélanger', team: ['Prof. Samuel Njoya', 'Marc Fotso'],
    progress: 0,
    tasks: [
      { id: 't9', label: 'Recrutement des mentors', done: false },
      { id: 't10', label: 'Sélection des étudiants', done: false },
      { id: 't11', label: 'Appariement mentor-étudiant', done: false },
      { id: 't12', label: 'Lancement du programme', done: false },
    ],
    photos: [], documents: ['schema_mentorat.pdf'],
    sourceIdeaId: 'id2', heritage: false,
  },
  {
    id: 'p3', number: 'PRJ-2024-003', title: 'Forage d\'un puits communautaire',
    description: 'Forage d\'un puits pour l\'approvisionnement en eau potable du village.',
    category: 'Infrastructure', location: 'Bafoussam, Cameroun',
    budget: 8000000, spent: 8000000, startDate: '2024-01-15', endDate: '2024-06-30',
    status: 'Terminé', manager: 'Robert Kana', team: ['Jean Menthong', 'Paul Tchoumi'],
    progress: 100,
    tasks: [
      { id: 't13', label: 'Étude hydrogéologique', done: true },
      { id: 't14', label: 'Forage', done: true },
      { id: 't15', label: 'Installation de la pompe', done: true },
      { id: 't16', label: 'Tests de qualité', done: true },
      { id: 't17', label: 'Inauguration', done: true },
    ],
    photos: [], documents: ['rapport_forage.pdf', 'certificat_qualite.pdf'],
    sourceIdeaId: null, heritage: true,
  },
  {
    id: 'p4', number: 'PRJ-2024-004', title: 'Distribution de kits scolaires',
    description: 'Distribution de kits scolaires aux enfants démunis de la communauté.',
    category: 'Social', location: 'Douala, Cameroun',
    budget: 3000000, spent: 3000000, startDate: '2024-08-01', endDate: '2024-09-15',
    status: 'Terminé', manager: 'Marie Kamga', team: ['Catherine Mbiya', 'Daniel Tchatchou'],
    progress: 100,
    tasks: [
      { id: 't18', label: 'Achat des kits', done: true },
      { id: 't19', label: 'Identification des bénéficiaires', done: true },
      { id: 't20', label: 'Distribution', done: true },
    ],
    photos: [], documents: ['liste_beneficiaires.pdf'],
    sourceIdeaId: null, heritage: true,
  },
  {
    id: 'p5', number: 'PRJ-2025-005', title: 'Campagne de reboisement',
    description: 'Plantation de 1000 arbres dans la région de Bafoussam pour lutter contre la déforestation.',
    category: 'Environnement', location: 'Bafoussam, Cameroun',
    budget: 2000000, spent: 800000, startDate: '2025-04-01', endDate: '2025-10-31',
    status: 'En cours', manager: 'Robert Kana', team: ['Eric Fotso', 'Yvan Kamga'],
    progress: 40,
    tasks: [
      { id: 't21', label: 'Achat des plants', done: true },
      { id: 't22', label: 'Sensibilisation de la population', done: true },
      { id: 't23', label: 'Plantation des arbres', done: false },
      { id: 't24', label: 'Suivi et entretien', done: false },
    ],
    photos: [], documents: ['plan_reboisement.pdf'],
    sourceIdeaId: null, heritage: false,
  },
  {
    id: 'p6', number: 'PRJ-2025-006', title: 'Centre de formation professionnelle',
    description: 'Création d\'un centre de formation professionnelle pour les jeunes de la communauté.',
    category: 'Éducation', location: 'Yaoundé, Cameroun',
    budget: 25000000, spent: 0, startDate: '2026-01-01', endDate: '2027-06-30',
    status: 'Planifié', manager: 'Prof. Samuel Njoya', team: ['Christine Bélanger'],
    progress: 0,
    tasks: [
      { id: 't25', label: 'Recherche de local', done: false },
      { id: 't26', label: 'Élaboration des programmes', done: false },
      { id: 't27', label: 'Recrutement des formateurs', done: false },
    ],
    photos: [], documents: [],
    sourceIdeaId: null, heritage: false,
  },
]

export const mockCategories: ProjectCategory[] = [
  { id: 'cat1', name: 'Infrastructure', color: '#3b82f6', description: 'Construction, rénovation et équipements', projectCount: 2 },
  { id: 'cat2', name: 'Éducation', color: '#10b981', description: 'Formation, mentorat et accompagnement scolaire', projectCount: 2 },
  { id: 'cat3', name: 'Social', color: '#f59e0b', description: 'Aide sociale, santé et solidarité', projectCount: 1 },
  { id: 'cat4', name: 'Agriculture', color: '#84cc16', description: 'Projets agricoles et de sécurité alimentaire', projectCount: 0 },
  { id: 'cat5', name: 'Technologie', color: '#6366f1', description: 'Digitalisation et outils numériques', projectCount: 0 },
  { id: 'cat6', name: 'Environnement', color: '#22c55e', description: 'Reboisement, assainissement et écologie', projectCount: 1 },
  { id: 'cat7', name: 'Événementiel', color: '#ec4899', description: 'Galas, fundraisings et événements', projectCount: 0 },
  { id: 'cat8', name: 'Finance', color: '#f97316', description: 'Microcrédit et projets financiers', projectCount: 0 },
]

export const mockCalendarEvents: CalendarEvent[] = [
  { id: 'ev1', title: 'Permis de construire - Siège social', date: '2025-08-15', type: 'deadline', projectId: 'p1', projectName: 'Construction siège social' },
  { id: 'ev2', title: 'Lancement programme mentorat', date: '2025-09-01', type: 'milestone', projectId: 'p2', projectName: 'Programme de mentorat' },
  { id: 'ev3', title: 'Fin campagne de reboisement', date: '2025-10-31', type: 'deadline', projectId: 'p5', projectName: 'Campagne de reboisement' },
  { id: 'ev4', title: 'Réunion équipe construction', date: '2025-08-10', type: 'meeting', projectId: 'p1', projectName: 'Construction siège social' },
  { id: 'ev5', title: 'Démarrage centre de formation', date: '2026-01-01', type: 'milestone', projectId: 'p6', projectName: 'Centre de formation' },
  { id: 'ev6', title: 'Réunion de clôture reboisement', date: '2025-10-25', type: 'meeting', projectId: 'p5', projectName: 'Campagne de reboisement' },
  { id: 'ev7', title: 'Fouilles et fondations', date: '2025-09-01', type: 'milestone', projectId: 'p1', projectName: 'Construction siège social' },
]

export const mockHeritage: HeritageItem[] = [
  { id: 'hr1', name: 'Puits communautaire', category: 'Infrastructure', location: 'Bafoussam, Cameroun', value: 8000000, completedDate: '2024-06-30', photoUrl: null, projectId: 'p3' },
  { id: 'hr2', name: 'Kits scolaires (200 enfants)', category: 'Social', location: 'Douala, Cameroun', value: 3000000, completedDate: '2024-09-15', photoUrl: null, projectId: 'p4' },
]
